[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/ewatercycle_destine/__init__.py"

[project]
name = "ewatercycle-destine"
description = "eWaterCycle plugin for using DestinE digital twin data."
readme = "README.md"
license = "Apache-2.0"
authors = [
  { name = "Mark Melotto", email = "markmelotto@tudelft.nl" },
]
keywords = ["ewatercycle", "hydrology"]
classifiers = [
  "Intended Audience :: Developers",
  "License :: OSI Approved :: Apache Software License",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
]

# Include here only the dependencies for the eWaterCycle wrapped model
dependencies = [
  "ewatercycle>=2.1.0",
]
dynamic = ["version"]

# This registers the plugin such that it is discoverable by eWaterCycle
[project.entry-points."ewatercycle.forcings"]
DestinEForcing = "ewatercycle_destine.forcing:DestinEForcing"
